### ISSUE TITLE
[SERVER-SIDE] server crash after launching

### ISSUE THREAD

**Issue by ShiroUsagi-san** [SalonDesDevs/SuperDungeonsDestroyers#3]
```
thread 'tokio-runtime-worker-1' panicked at 'attempt to add with overflow', super-dungeons-destroyers-server/src/game/game_loop.rs:74:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Got disconnected
thread 'tokio-runtime-worker-2' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:1051:5
```
after a while, the server just crashed with this panic message.

# Steps to reproduce:
- launch the server-side and wait... After a while, it crashed

**Comment by lightdiscord** [comment]
Can't reproduce, be more precise

EDIT: You also need to start a client
